---
version: '3'

services:
  zookeeper-service:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-broker-service:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-service
    ports:
      - 29092:29092
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-service:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka-broker-service
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=item-topic --if-not-exists --bootstrap-server=kafka-broker-service:9092"

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka-broker-service
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka-broker-service:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021